import { Header } from "@/components/header";
import { StoreProviders } from "@/store/provider";
import type { Metadata } from "next";
import { NextIntlClientProvider, useMessages } from "next-intl";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
	params: { locale },
}: Readonly<{
	children: React.ReactNode;
	params: { locale: string };
}>) {
	const messages = useMessages();

	return (
		<html lang={locale}>
			<body className={inter.className}>
				<StoreProviders>
					<NextIntlClientProvider locale={locale} messages={messages}>
						<Header />
						<div className="container">{children}</div>
					</NextIntlClientProvider>
				</StoreProviders>
			</body>
		</html>
	);
}
